# This workflow builds your project and deploys it to GitHub Pages.
# It is designed to work with the built-in GitHub Pages deployment process.
# Place this file in your .github/workflows/ directory.

name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Change this to your default branch if it's not main
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          # VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set as repository secrets
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          # The path must point to your build output directory (e.g., dist, build, public)
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure GitHub Pages
        id: deployment
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
